name: Continuous deployment

on:
  push:
    branches:
      - master

jobs:
  deployBackend:
    name: Deploy backend to heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "timo-backend"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Run migrations
        run: heroku run "POOL_SIZE=2 cd timo_backend && mix ecto.migrate"

  deployFrontend:
    name: Deploy frontend to surge.sh with own domain
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install ember
        run: npm install -g ember-cli@3.12.0

      - name: Yarn dependencies
        working-directory: ./timo_frontend
        run: yarn install

      - name: Build ember project
        working-directory: ./timo_frontend
        run: |
          ember build --environment production
          mv dist/index.html dist/200.html

      - name: Install surge
        run: npm install -g surge

      - name: Deploy to timo.mimiquate.xyz with surge
        working-directory: ./timo_frontend
        run: surge dist timo.mimiquate.xyz --token ${{ secrets.SURGE_TOKEN }}
