name: Continuous Integration

on: [push]

jobs:
  buildAndTestBackend:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.1
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2.1'
          elixir-version: '1.9.4'

      - name: Get phoenix dependencies
        working-directory: ./timo_backend
        run: mix deps.get

      - name: Check format
        working-directory: ./timo_backend
        run: mix format --check-formatted

      - name: Run phoenix tests
        working-directory: ./timo_backend
        run: mix test

  buildAndTestFrontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install ember
        run: npm install -g ember-cli

      - name: Yarn dependencies
        working-directory: ./timo_frontend
        run: yarn install

      - name: Run ember tests
        working-directory: ./timo_frontend
        run: ember test
