name: Continuous Integration

on: [push]

jobs:
  buildAndTestBackend:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.1
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2.1'
          elixir-version: '1.9.4'

      - name: Get phoenix dependencies
        run: |
          cd timo_backend
          mix deps.get

      - name: Check format
        run: |
          cd timo_backend
          mix format --check-formatted

      - name: Run phoenix tests
        run: |
          cd timo_backend
          mix test
