name: Timo workflow

on: [push]

jobs:
  build_and_test_backend:
    name: Builds and test backend
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.1
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2.1'
          elixir-version: '1.9.4'

      - name: Get phoenix dependencies
        working-directory: ./timo_backend
        run: mix deps.get

      - name: Check format
        working-directory: ./timo_backend
        run: mix format --check-formatted

      - name: Run phoenix tests
        working-directory: ./timo_backend
        run: mix test

  build_and_test_frontend:
    name: Builds and test frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install ember
        run: npm install -g ember-cli@3.12.0

      - name: Yarn dependencies
        working-directory: ./timo_frontend
        run: yarn install

      - name: Run ember tests
        working-directory: ./timo_frontend
        run: ember test

  deploy_backend:
    name: Deploy backend to heroku
    needs: [build_and_test_backend, build_and_test_frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "timo-backend"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Run migrations
        run: heroku run "POOL_SIZE=2 cd timo_backend && mix ecto.migrate"

  deploy_frontend:
    name: Deploy frontend to Netlify with own domain
    needs: [build_and_test_backend, build_and_test_frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install ember
        run: npm install -g ember-cli@3.12.0

      - name: Yarn dependencies
        working-directory: ./timo_frontend
        run: yarn install

      - name: Build ember project
        working-directory: ./timo_frontend
        run: ember build --environment production

      - name: Install netlify-cli
        run: npm install netlify-cli -g

      - name: Deploy to timo.mimiquate.xyz with netlify-cli
        run: netlify deploy --prod --dir=timo_frontend/dist --auth={{ secrets.NETFLY_AUTH }} --site={{ secrets.NETLIFY_SITE_ID }}
