name: Timo workflow

on: [push]

jobs:
  build_and_test_backend:
    name: Builds and test backend
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          version-file: './timo_backend/.tool-versions'
          version-type: 'strict'

      - name: Cache code and deps
        uses: actions/cache@v4
        with:
          path: |
            ./timo_backend/_build
            ./timo_backend/deps
          key: ${{runner.os}}-${{steps.beam.outputs.elixir-version}}-${{steps.beam.outputs.otp-version}}-${{hashFiles('mix.lock')}}

      - name: Get phoenix dependencies
        working-directory: ./timo_backend
        run: mix deps.get

      - name: Compile with warnings as errors
        working-directory: ./timo_backend
        run: mix compile --warnings-as-errors

      - name: Check format
        working-directory: ./timo_backend
        run: mix format --check-formatted

      - name: Run phoenix tests
        working-directory: ./timo_backend
        run: mix test

  build_and_test_frontend:
    name: Builds and test frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install ember
        run: npm install -g ember-cli@3.28.3

      - name: Yarn dependencies
        working-directory: ./timo_frontend
        run: yarn install

      - name: Run ember tests
        working-directory: ./timo_frontend
        run: ember test

  deploy_backend:
    name: Deploy backend to heroku
    needs: [build_and_test_backend, build_and_test_frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "timo-backend"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Run migrations
        run: heroku run "POOL_SIZE=2 cd timo_backend && mix ecto.migrate"

  deploy_frontend:
    name: Deploy frontend to Netlify with own domain
    needs: [build_and_test_backend, build_and_test_frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install ember
        run: npm install -g ember-cli@3.28.3

      - name: Yarn dependencies
        working-directory: ./timo_frontend
        run: yarn install

      - name: Build ember project
        working-directory: ./timo_frontend
        run: ember build --environment production

      - name: Install netlify-cli
        run: npm install netlify-cli -g

      - name: Deploy to timo.mimiquate.xyz with netlify-cli
        run: netlify deploy --prod --dir=timo_frontend/dist --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
